/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Booking.Insert_bookings;
import Database.DB_conn;
import Invoice.DBInvoice;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MaC
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    int xMouse;
    int yMouse;
    String path = "";
    double CONSULTATION = 0;
    double FILLINGS = 0;
    double EXTRACTIONS = 0;
    double FULL = 0;
    double ROOT = 0;
    double IMPLANTS = 0;
    double DENTAL = 0;
    double TEETH = 0;
    double INLAYS = 0;
    double ORTHODONTICS = 0;
    double OTHER = 0;
    double total = 0;
    String PID;
    private String log_name;
    private String user_role;

    public Invoice() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
//        
//         try {
//            DB_conn.initFirbase();
//        } catch (IOException ex) {
//            Logger.getLogger(Insert_bookings.class.getName()).log(Level.SEVERE, null, ex);
//        } 
//        
    }

    public Invoice(String log_name, String user_role) {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        this.log_name = log_name;
        this.user_role = user_role;
//        
//         try {
//            DB_conn.initFirbase();
//        } catch (IOException ex) {
//            Logger.getLogger(Insert_bookings.class.getName()).log(Level.SEVERE, null, ex);
//        } 
//        
    }

    public Invoice(String Name, String PPID, String log_name, String user_role) {
        //txtAge.setText(Integer.toString(Age));
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        this.log_name = log_name;
        this.user_role = user_role;
        txtName.setText(Name);

        PID = PPID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCONSULTATION = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFILLINGS = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtEXTRACTIONS = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtFULL = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtROOT = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtIMPLANTS = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtDENTAL = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtTEETH = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        txtINLAYS = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        txtORTHODONTICS = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        txtOTHER = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        btnSearch = new keeptoo.KButton();
        btnSearch1 = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnTotal = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkBorderRadius(25);
        kGradientPanel1.setkEndColor(new java.awt.Color(61, 114, 180));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(82, 82, 82));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setForeground(new java.awt.Color(255, 0, 51));
        kGradientPanel2.setkBorderRadius(25);
        kGradientPanel2.setkEndColor(new java.awt.Color(240, 240, 240));
        kGradientPanel2.setkStartColor(new java.awt.Color(240, 240, 240));
        kGradientPanel2.setOpaque(false);

        txtName.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AMOUNT (Rs.)");

        txtCONSULTATION.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtCONSULTATION.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCONSULTATION.setBorder(null);
        txtCONSULTATION.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCONSULTATIONFocusGained(evt);
            }
        });
        txtCONSULTATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCONSULTATIONActionPerformed(evt);
            }
        });
        txtCONSULTATION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCONSULTATIONKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCONSULTATIONKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel7.setText("FILLINGS (TEMPORARY/ GIC/COMPOSITE/AMALGUM) ");

        txtFILLINGS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtFILLINGS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFILLINGS.setBorder(null);
        txtFILLINGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFILLINGSActionPerformed(evt);
            }
        });
        txtFILLINGS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFILLINGSKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFILLINGSKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        txtEXTRACTIONS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtEXTRACTIONS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEXTRACTIONS.setBorder(null);
        txtEXTRACTIONS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEXTRACTIONSActionPerformed(evt);
            }
        });
        txtEXTRACTIONS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEXTRACTIONSKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEXTRACTIONSKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel17.setText("EXTRACTIONS ");

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));

        txtFULL.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtFULL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFULL.setBorder(null);
        txtFULL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFULLActionPerformed(evt);
            }
        });
        txtFULL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFULLKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFULLKeyTyped(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel18.setText("FULL MOUTH SCALING ");

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel19.setText("ROOT CANAL TREATMENTS ");

        txtROOT.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtROOT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtROOT.setBorder(null);
        txtROOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtROOTActionPerformed(evt);
            }
        });
        txtROOT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtROOTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtROOTKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));

        txtIMPLANTS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtIMPLANTS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIMPLANTS.setBorder(null);
        txtIMPLANTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMPLANTSActionPerformed(evt);
            }
        });
        txtIMPLANTS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIMPLANTSKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIMPLANTSKeyTyped(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel20.setText("IMPLANTS ");

        txtDENTAL.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtDENTAL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDENTAL.setBorder(null);
        txtDENTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDENTALActionPerformed(evt);
            }
        });
        txtDENTAL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDENTALKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDENTALKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel21.setText("DENTAL CROWNS/VENEERS/ BRIDGES ");

        jSeparator7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel22.setText("TEETH WHITENING ");

        txtTEETH.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtTEETH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTEETH.setBorder(null);
        txtTEETH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTEETHActionPerformed(evt);
            }
        });
        txtTEETH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTEETHKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTEETHKeyTyped(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel23.setText("INLAYS/ ONLAYS");

        txtINLAYS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtINLAYS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtINLAYS.setBorder(null);
        txtINLAYS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtINLAYSActionPerformed(evt);
            }
        });
        txtINLAYS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtINLAYSKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtINLAYSKeyTyped(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel24.setText("ORTHODONTICS ");

        txtORTHODONTICS.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtORTHODONTICS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtORTHODONTICS.setBorder(null);
        txtORTHODONTICS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtORTHODONTICSActionPerformed(evt);
            }
        });
        txtORTHODONTICS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtORTHODONTICSKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtORTHODONTICSKeyTyped(evt);
            }
        });

        jSeparator10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel25.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel25.setText("OTHER ");

        txtOTHER.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtOTHER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOTHER.setBorder(null);
        txtOTHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOTHERActionPerformed(evt);
            }
        });
        txtOTHER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOTHERKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOTHERKeyTyped(evt);
            }
        });

        jSeparator11.setBackground(new java.awt.Color(204, 204, 204));

        btnSearch.setText("Cancel");
        btnSearch.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSearch.setkAllowGradient(false);
        btnSearch.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnSearch.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSearch1.setText("Submit");
        btnSearch1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSearch1.setkAllowGradient(false);
        btnSearch1.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnSearch1.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnSearch1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel8.setText("CONSULTATION ");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel9.setText("Age:");

        txtAge.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });

        btnTotal.setText("Calculate Total");
        btnTotal.setFocusable(false);
        btnTotal.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnTotal.setkAllowGradient(false);
        btnTotal.setkBackGroundColor(new java.awt.Color(48, 67, 82));
        btnTotal.setkHoverColor(new java.awt.Color(63, 87, 107));
        btnTotal.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-calculator-48.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248)
                .addComponent(txtCONSULTATION, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtFILLINGS, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtEXTRACTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtFULL, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtROOT, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtIMPLANTS, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtDENTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtTEETH, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtINLAYS, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtORTHODONTICS, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtOTHER, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9))
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8))
                    .addComponent(txtCONSULTATION, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addComponent(txtFILLINGS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17))
                    .addComponent(txtEXTRACTIONS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18))
                    .addComponent(txtFULL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel19))
                    .addComponent(txtROOT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel20))
                    .addComponent(txtIMPLANTS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel21))
                    .addComponent(txtDENTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel22))
                    .addComponent(txtTEETH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel23))
                    .addComponent(txtINLAYS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel24))
                    .addComponent(txtORTHODONTICS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel25))
                    .addComponent(txtOTHER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 711, 820));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cash-receipt-80.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 6, -1, 70));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Billing");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mini.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 6, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 6, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-go-back-70.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
        });
        kGradientPanel1.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        //login log = new login();
        this.setState(Invoice.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        home hm = new home(log_name, user_role);
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtCONSULTATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCONSULTATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCONSULTATIONActionPerformed

    private void txtCONSULTATIONKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCONSULTATIONKeyReleased

    }//GEN-LAST:event_txtCONSULTATIONKeyReleased

    private void txtFILLINGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFILLINGSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFILLINGSActionPerformed

    private void txtFILLINGSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFILLINGSKeyReleased

    }//GEN-LAST:event_txtFILLINGSKeyReleased

    private void txtEXTRACTIONSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEXTRACTIONSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEXTRACTIONSActionPerformed

    private void txtEXTRACTIONSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEXTRACTIONSKeyReleased

    }//GEN-LAST:event_txtEXTRACTIONSKeyReleased

    private void txtFULLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFULLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFULLActionPerformed

    private void txtFULLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFULLKeyReleased

    }//GEN-LAST:event_txtFULLKeyReleased

    private void txtROOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtROOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtROOTActionPerformed

    private void txtROOTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtROOTKeyReleased

    }//GEN-LAST:event_txtROOTKeyReleased

    private void txtIMPLANTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMPLANTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMPLANTSActionPerformed

    private void txtIMPLANTSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIMPLANTSKeyReleased

    }//GEN-LAST:event_txtIMPLANTSKeyReleased

    private void txtDENTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDENTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDENTALActionPerformed

    private void txtDENTALKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDENTALKeyReleased

    }//GEN-LAST:event_txtDENTALKeyReleased

    private void txtTEETHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTEETHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTEETHActionPerformed

    private void txtTEETHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTEETHKeyReleased

    }//GEN-LAST:event_txtTEETHKeyReleased

    private void txtINLAYSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtINLAYSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtINLAYSActionPerformed

    private void txtINLAYSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINLAYSKeyReleased

    }//GEN-LAST:event_txtINLAYSKeyReleased

    private void txtORTHODONTICSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtORTHODONTICSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtORTHODONTICSActionPerformed

    private void txtORTHODONTICSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtORTHODONTICSKeyReleased

    }//GEN-LAST:event_txtORTHODONTICSKeyReleased

    private void txtOTHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOTHERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOTHERActionPerformed

    private void txtOTHERKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOTHERKeyReleased

    }//GEN-LAST:event_txtOTHERKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed

        try {
            JFileChooser jf = new JFileChooser();
            jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            jf.showSaveDialog(null);
            path = jf.getSelectedFile().getAbsolutePath();

            if (calTotal()) {
                toPDF();
                invoiceLedger();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "There is error with File Location.\n   Try Again!", "Location Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnSearch1ActionPerformed
    public void toPDF() {
        try {
            JasperReport jasperReport = JasperCompileManager.compileReport(getClass().getResourceAsStream("/Invoice/newReport.jrxml"));
            //InputStream jasper1 = getClass().getResourceAsStream("src/Interfaces/newReport.jrxml");        
            JRDataSource jrDataSource = new JREmptyDataSource();
            Map<String, Object> parameters = new HashMap<String, Object>();
            parameters.put("Name", txtName.getText());
            parameters.put("Age", txtAge.getText());
            parameters.put("CONSULTATION", txtCONSULTATION.getText());
            parameters.put("FILLINGS", txtFILLINGS.getText());
            parameters.put("EXTRACTIONS", txtEXTRACTIONS.getText());
            parameters.put("FULL", txtFULL.getText());
            parameters.put("ROOT", txtROOT.getText());
            parameters.put("IMPLANTS", txtIMPLANTS.getText());
            parameters.put("DENTAL", txtDENTAL.getText());
            parameters.put("TEETH", txtTEETH.getText());
            parameters.put("INLAYS", txtINLAYS.getText());
            parameters.put("ORTHODONTICS", txtORTHODONTICS.getText());
            parameters.put("OTHER", txtOTHER.getText());
            parameters.put("Total", txtTotal.getText());
            JasperPrint jasperprint = JasperFillManager.fillReport(jasperReport, parameters, jrDataSource);

            DateFormat dateFormat = new SimpleDateFormat("[yyyy.MM.dd][HH.mm.ss]");
            Date date = new Date();
            JOptionPane.showMessageDialog(null, dateFormat.format(date));

            JasperExportManager.exportReportToPdfFile(jasperprint, path + "\\" + txtName.getText() + dateFormat.format(date) + ".pdf");
            if (Desktop.isDesktopSupported()) {
                try {
                    File myFile = new File(path + "\\" + txtName.getText() + dateFormat.format(date) + ".pdf");
                    Desktop.getDesktop().open(myFile);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    private void invoiceLedger() {
        //----------------------------------------------------------------------------------------------------------------        

        //inrtBoks.Insert_tempbookings(new_bookings);
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference myRef = database.getReference("Dentz/Invoices");

        LocalDate now1 = LocalDate.now(); //get Local System date
        Date today = java.sql.Date.valueOf(now1);
//----------------------------------------------------------------------------------------------------------------        
        DBInvoice invoice = new DBInvoice();

        invoice.setName(txtName.getText());
        invoice.setPID(PID);
        invoice.setTotal(txtTotal.getText());
        invoice.setDate(today.toString());

        myRef.push().setValue(invoice, new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError de, DatabaseReference dr) {
                if (de != null) {
                    JOptionPane.showMessageDialog(null, dr);
                } else {
                    JOptionPane.showMessageDialog(null, "Data Saved Succesfully");
                }

                throw new UnsupportedOperationException("Not supported yet.");
            }
        });

    }
    private static DecimalFormat df = new DecimalFormat("0.00");

    private boolean calTotal() {
        try {
            total = Double.parseDouble((txtCONSULTATION.getText().isEmpty()) ? "0" : txtCONSULTATION.getText())
                    + Double.parseDouble((txtFILLINGS.getText().isEmpty()) ? "0" : txtFILLINGS.getText())
                    + Double.parseDouble((txtEXTRACTIONS.getText().isEmpty()) ? "0" : txtEXTRACTIONS.getText())
                    + Double.parseDouble((txtFULL.getText().isEmpty()) ? "0" : txtFULL.getText())
                    + Double.parseDouble((txtROOT.getText().isEmpty()) ? "0" : txtROOT.getText())
                    + Double.parseDouble((txtIMPLANTS.getText().isEmpty()) ? "0" : txtIMPLANTS.getText())
                    + Double.parseDouble((txtDENTAL.getText().isEmpty()) ? "0" : txtDENTAL.getText())
                    + Double.parseDouble((txtTEETH.getText().isEmpty()) ? "0" : txtTEETH.getText())
                    + Double.parseDouble((txtINLAYS.getText().isEmpty()) ? "0" : txtINLAYS.getText())
                    + Double.parseDouble((txtORTHODONTICS.getText().isEmpty()) ? "0" : txtORTHODONTICS.getText())
                    + Double.parseDouble((txtOTHER.getText().isEmpty()) ? "0" : txtOTHER.getText());
            txtTotal.setText(String.valueOf(df.format(total)));
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "There is error with values.\n   Type Again!", "Value Error", JOptionPane.ERROR_MESSAGE);
            txtCONSULTATION.setText("");
            txtFILLINGS.setText("");
            txtEXTRACTIONS.setText("");
            txtFULL.setText("");
            txtROOT.setText("");
            txtIMPLANTS.setText("");
            txtDENTAL.setText("");
            txtTEETH.setText("");
            txtINLAYS.setText("");
            txtORTHODONTICS.setText("");
            txtOTHER.setText("");
            return false;
        }

    }

    private void txtCONSULTATIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCONSULTATIONKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();

            }
        }


    }//GEN-LAST:event_txtCONSULTATIONKeyTyped

    private void txtFILLINGSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFILLINGSKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();

            }
        }

    }//GEN-LAST:event_txtFILLINGSKeyTyped

    private void txtEXTRACTIONSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEXTRACTIONSKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtEXTRACTIONSKeyTyped

    private void txtFULLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFULLKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtFULLKeyTyped

    private void txtROOTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtROOTKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtROOTKeyTyped

    private void txtIMPLANTSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIMPLANTSKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtIMPLANTSKeyTyped

    private void txtDENTALKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDENTALKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtDENTALKeyTyped

    private void txtTEETHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTEETHKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtTEETHKeyTyped

    private void txtINLAYSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtINLAYSKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtINLAYSKeyTyped

    private void txtORTHODONTICSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtORTHODONTICSKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtORTHODONTICSKeyTyped

    private void txtOTHERKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOTHERKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            if (enter != '.') {
                evt.consume();
            }
        }

    }//GEN-LAST:event_txtOTHERKeyTyped

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyReleased

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtCONSULTATIONFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCONSULTATIONFocusGained

    }//GEN-LAST:event_txtCONSULTATIONFocusGained

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed

        calTotal();
    }//GEN-LAST:event_btnTotalActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            Runtime.getRuntime().exec("calc");
        } catch (IOException ex) {
            Logger.getLogger(Invoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    ImageIcon iconEntered = new ImageIcon("img/icons8-go-back-702.png");
    ImageIcon iconExited = new ImageIcon("img/icons8-go-back-70.png");
    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        home hm = new home(log_name, user_role);
        hm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        lblBack.setIcon(iconEntered);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        lblBack.setIcon(iconExited);
    }//GEN-LAST:event_lblBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMinimize;
    private keeptoo.KButton btnSearch;
    private keeptoo.KButton btnSearch1;
    private keeptoo.KButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCONSULTATION;
    private javax.swing.JTextField txtDENTAL;
    private javax.swing.JTextField txtEXTRACTIONS;
    private javax.swing.JTextField txtFILLINGS;
    private javax.swing.JTextField txtFULL;
    private javax.swing.JTextField txtIMPLANTS;
    private javax.swing.JTextField txtINLAYS;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtORTHODONTICS;
    private javax.swing.JTextField txtOTHER;
    private javax.swing.JTextField txtROOT;
    private javax.swing.JTextField txtTEETH;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
