/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;
import Database.DB_conn;
import Users.User;
import Validation.Email;
import Validation.Errormsg;
import Validation.Password;
import com.google.firebase.auth.EmailIdentifier;
import com.google.firebase.auth.hash.Md5;
//import Validation.Email;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import java.awt.Color;
import java.awt.Frame;
import java.io.IOException;
import java.net.PasswordAuthentication;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Darkness
 */
public class user_reg extends javax.swing.JFrame {

    /**
     * Creates new form user_reg
     */
     int xMouse;
    int yMouse;
    String userID = "";
    public user_reg() {
        initComponents();
        btn_update.setEnabled(false);
        setBackground(new Color(0, 0, 0, 0));
//        try {
//             DB_conn.initFirbase();
//         } catch (IOException ex) {
//             Logger.getLogger(user_reg.class.getName()).log(Level.SEVERE, null, ex);
//         }

        //retrive Usernames which exist in database
            dataload();        
    }
public user_reg(User update){
    initComponents();
    btn_Add.setEnabled(false);
    
    userID = update.getUid();
    
    //convet String (update.getDOB) to Date type
    LocalDate cladate = LocalDate.parse(update.getDOB());
    java.util.Date date = java.sql.Date.valueOf(cladate);    
    //--------------------------------------------------------
    
   //set Values in Update Object to Form Feilds
    txt_usrname.setText(update.getName());
    txt_NIC.setText(update.getNIC());    
    Date_DOB.setDate(date);
    txt_Email.setText(update.getEmail());
    txt_PhnNm.setText(Integer.toString(update.getMobileNm()));
    txtAr_Address.setText(update.getAdress());
    txt_UsrNm.setText(update.getUserName());
    Pass_pswrd.setText(null);
        
    if(update.getJobRole().endsWith("User")){
        combo_JRole.setSelectedIndex(0);
        
    }else if(update.getJobRole().endsWith("Doctor")){
        combo_JRole.setSelectedIndex(1);
    }else if (update.getJobRole().endsWith("Admin")) {
        combo_JRole.setSelectedIndex(2);
    }
//-----------------------------------------------------------
     //retrive Usernames which exist in database
       dataload();  
    
    }
    ArrayList<User> allusers1= new ArrayList<User>();
     //data load into alluser array list
    public void dataload(){
          
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference myRef = database.getReference("Dentz/Users");
        
         myRef.addListenerForSingleValueEvent(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot dataSnapshot) {
                  
                 Iterable<DataSnapshot> children = dataSnapshot.getChildren();
               
                  for(DataSnapshot child:children){
                      User usr=child.getValue(User.class);
                      allusers1.add(usr);  
                      System.out.println(allusers1.size());                 
                  }                              
                }                
                @Override
                public void onCancelled(DatabaseError databaseError) {
                  System.out.println("The read failed: " + databaseError.getCode());
                }
              });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnMinimize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_usrname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_NIC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_PhnNm = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Date_DOB = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAr_Address = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txt_UsrNm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Pass_pswrd = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        combo_JRole = new javax.swing.JComboBox<>();
        btn_Add = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        btn_update = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration");
        setName("user_reg"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkBorderRadius(25);
        kGradientPanel1.setkEndColor(new java.awt.Color(47, 7, 67));
        kGradientPanel1.setkStartColor(new java.awt.Color(67, 198, 172));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mini.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 11, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 11, -1, -1));

        kGradientPanel2.setkBorderRadius(25);
        kGradientPanel2.setkEndColor(new java.awt.Color(240, 240, 240));
        kGradientPanel2.setkStartColor(new java.awt.Color(240, 240, 240));
        kGradientPanel2.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel3.setText("Name: ");

        txt_usrname.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_usrname.setForeground(new java.awt.Color(102, 102, 102));
        txt_usrname.setToolTipText("Enter Your Name");
        txt_usrname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_usrname.setCaretColor(new java.awt.Color(153, 0, 153));
        txt_usrname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_usrname.setName(""); // NOI18N
        txt_usrname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usrnameMouseClicked(evt);
            }
        });
        txt_usrname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usrnameActionPerformed(evt);
            }
        });
        txt_usrname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usrnameKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel5.setText("NIC: ");

        txt_NIC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_NIC.setForeground(new java.awt.Color(102, 102, 102));
        txt_NIC.setToolTipText("Enter Your National Identity Card Number");
        txt_NIC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_NIC.setCaretColor(new java.awt.Color(153, 0, 153));
        txt_NIC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_NIC.setName(""); // NOI18N
        txt_NIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_NICMouseClicked(evt);
            }
        });
        txt_NIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NICActionPerformed(evt);
            }
        });
        txt_NIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NICKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel9.setText("E-Mail: ");

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(102, 102, 102));
        txt_Email.setToolTipText("Enter Your E-mail");
        txt_Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_Email.setCaretColor(new java.awt.Color(153, 0, 153));
        txt_Email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Email.setName(""); // NOI18N
        txt_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_EmailMouseClicked(evt);
            }
        });
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        txt_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_EmailKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel10.setText("Mobile:");

        txt_PhnNm.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_PhnNm.setForeground(new java.awt.Color(102, 102, 102));
        txt_PhnNm.setToolTipText("Enter Your Mobile Number");
        txt_PhnNm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_PhnNm.setCaretColor(new java.awt.Color(153, 0, 153));
        txt_PhnNm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_PhnNm.setName(""); // NOI18N
        txt_PhnNm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PhnNmMouseClicked(evt);
            }
        });
        txt_PhnNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PhnNmActionPerformed(evt);
            }
        });
        txt_PhnNm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PhnNmKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel12.setText("DOB:");

        Date_DOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Date_DOB.setToolTipText("Birthday");

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel13.setText("Home Address:");

        txtAr_Address.setColumns(20);
        txtAr_Address.setRows(5);
        txtAr_Address.setToolTipText("Enter Your Current Address");
        txtAr_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtAr_Address);
        txtAr_Address.getAccessibleContext().setAccessibleDescription("");

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel15.setText("User Name:");

        txt_UsrNm.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_UsrNm.setForeground(new java.awt.Color(102, 102, 102));
        txt_UsrNm.setToolTipText("User Name for Login");
        txt_UsrNm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txt_UsrNm.setCaretColor(new java.awt.Color(153, 0, 153));
        txt_UsrNm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_UsrNm.setName(""); // NOI18N
        txt_UsrNm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_UsrNmMouseClicked(evt);
            }
        });
        txt_UsrNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsrNmActionPerformed(evt);
            }
        });
        txt_UsrNm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UsrNmKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel16.setText("Password: ");

        Pass_pswrd.setToolTipText("Password for Login");

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jLabel17.setText("Job role: ");

        combo_JRole.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combo_JRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Doctor", "Admin" }));
        combo_JRole.setToolTipText("Your Job");

        btn_Add.setBorder(null);
        btn_Add.setForeground(new java.awt.Color(240, 240, 240));
        btn_Add.setText("Add User");
        btn_Add.setToolTipText("");
        btn_Add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Add.setkAllowGradient(false);
        btn_Add.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        btn_Add.setkBorderRadius(35);
        btn_Add.setkHoverColor(new java.awt.Color(102, 102, 102));
        btn_Add.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddMouseClicked(evt);
            }
        });
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        kButton3.setBorder(null);
        kButton3.setForeground(new java.awt.Color(240, 240, 240));
        kButton3.setText("Cancel");
        kButton3.setToolTipText("");
        kButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        kButton3.setkAllowGradient(false);
        kButton3.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        kButton3.setkBorderRadius(35);
        kButton3.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        btn_update.setBorder(null);
        btn_update.setForeground(new java.awt.Color(240, 240, 240));
        btn_update.setText("Update");
        btn_update.setToolTipText("");
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_update.setkAllowGradient(false);
        btn_update.setkBackGroundColor(new java.awt.Color(51, 51, 51));
        btn_update.setkBorderRadius(35);
        btn_update.setkHoverColor(new java.awt.Color(102, 102, 102));
        btn_update.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(80, 80, 80)
                        .addComponent(combo_JRole, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_usrname, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(90, 90, 90))
                                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(107, 107, 107)))
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Date_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_PhnNm, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_UsrNm, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(68, 68, 68)
                            .addComponent(Pass_pswrd, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_usrname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(Date_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_PhnNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(txt_UsrNm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(Pass_pswrd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGap(3, 3, 3)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_JRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(6, 6, 6)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        txt_PhnNm.getAccessibleContext().setAccessibleDescription("");
        txt_UsrNm.getAccessibleContext().setAccessibleDescription("");
        Pass_pswrd.getAccessibleContext().setAccessibleDescription("");
        combo_JRole.getAccessibleContext().setAccessibleName("");
        combo_JRole.getAccessibleContext().setAccessibleDescription("");

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 908, 607));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add User");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-user-male-80.png"))); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 700));

        setSize(new java.awt.Dimension(930, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
  int validation = 0;     
         Errormsg error = new Errormsg();
         
        // check whether input feilds are empty or not
        if(txt_usrname.getText().isEmpty()){
            error.show_msg("Enter Your Name");            
        }else if(txt_NIC.getText().isEmpty()){
            error.show_msg("Enter Your National Identity Card Number");
        }else if(Date_DOB.getDate() == null){
            error.show_msg("Enter Your Birthday");
        }else if(txt_Email.getText().isEmpty()){
            error.show_msg("Enter Your Email Address");
        }else if(txt_PhnNm.getText().isEmpty()){
            error.show_msg("Enter your Contact Number");       
        }else if(txtAr_Address.getText().isEmpty()){
            error.show_msg("Enter Your Address");
        }else if(txt_UsrNm.getText().isEmpty()){
            error.show_msg("Enter Username");
        }else if(Pass_pswrd.getText().isEmpty()){
            error.show_msg("Enter Password");
        }else {
            // check Validation of E-mail Address
           Email eval = new Email();
            if(eval.validate(txt_Email.getText())){
                validation++;
            }else{
                error.show_msg("Email Address invalid.");
            }
            //check whether User name is already use or not
            int username_check = 1;
            String x = txt_UsrNm.getText();
                for(int i = 0; i<allusers1.size();i++){
                    if(x.equals(allusers1.get(i).getUserName())){
//                        System.out.println("user names are equal");
                        username_check = 0;                        
                    }else{//                       
//                    System.out.println("not Equals");
                    }
                }
            if(username_check==1){
                validation++;
//                System.out.println("pass");
            }else{
                error.show_msg("Sorry.....This Username is already taken.");
            }
            
             if(validation == 2){                 
                Password pass = new Password();               
                
                 SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                 String thedate = dateFormat.format(Date_DOB.getDate());
                
                //create user object to store all the details in the form must validate        
                    User usr= new User();
                    usr.setName(txt_usrname.getText());
                    usr.setNIC(txt_NIC.getText());
                    usr.setMobileNm(Integer.valueOf(txt_PhnNm.getText()));
                    usr.setDOB(thedate);
                    usr.setAdress(txtAr_Address.getText());
                    usr.setEmail(txt_Email.getText());
                    usr.setUserName(txt_UsrNm.getText());
                    
                    try {
                        usr.setPassword(pass.passwordEncord(Pass_pswrd.getText().toString().trim()));
                    } catch (NoSuchAlgorithmException ex) {
                            Logger.getLogger(user_reg.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                    
                    usr.setJobRole(combo_JRole.getSelectedItem().toString());

        //Establish connection to the firebase Database and give location to the saving node
            FirebaseDatabase database = FirebaseDatabase.getInstance();
            DatabaseReference myRef = database.getReference("Dentz/Users");

            Map<String, Object> userUpdates = new HashMap<>();
            userUpdates.put(userID, usr);

            if(myRef.updateChildrenAsync(userUpdates).isCancelled()){
                JOptionPane.showMessageDialog(this, "Update Failed",null,JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Update Completed");
                this.dispose();
            }
            
            }
        }


    }//GEN-LAST:event_btn_updateActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
//        this.dispose();
        int result = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Cancel?",null,JOptionPane.YES_NO_OPTION);
        
        if(result == 0){
            this.dispose();
        }else{
            System.out.println(result);            
        }   
        
    }//GEN-LAST:event_kButton3ActionPerformed

    
    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
      int validation = 0;
        
        Errormsg error = new Errormsg();
        // check whether input feilds are empty or not
        if(txt_usrname.getText().isEmpty()){
            error.show_msg("Enter Your Name");            
        }else if(txt_NIC.getText().isEmpty()){
            error.show_msg("Enter Your National Identity Card Number");
        }else if(Date_DOB.getDate() == null){
            error.show_msg("Enter Your Birthday");
        }else if(txt_Email.getText().isEmpty()){
            error.show_msg("Enter Your Email Address");
        }else if(txt_PhnNm.getText().isEmpty()){
            error.show_msg("Enter your Contact Number");       
        }else if(txtAr_Address.getText().isEmpty()){
            error.show_msg("Enter Your Address");
        }else if(txt_UsrNm.getText().isEmpty()){
            error.show_msg("Enter Username");
        }else if(Pass_pswrd.getText().isEmpty()){
            error.show_msg("Enter Password");
        }else {
            // check Validation of E-mail Address
           Email eval = new Email();
            if(eval.validate(txt_Email.getText())){
                validation++;
            }else{
                error.show_msg("Email Address invalid.");
            }
            //check whether User name is already use or not
            int username_check = 1;
            String x = txt_UsrNm.getText();
                for(int i = 0; i<allusers1.size();i++){
                    if(x.equals(allusers1.get(i).getUserName())){
//                        System.out.println("user names are equal");
                        username_check = 0;                        
                    }else{//                       
//                    System.out.println("not Equals");
                    }
                }
            if(username_check==1){
                validation++;
//                System.out.println("pass");
            }else{
                error.show_msg("Sorry.....This Username is already taken.");
            }
            
             if(validation == 2){                 
                Password pass = new Password();               
                
                 SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                 String thedate = dateFormat.format(Date_DOB.getDate());
                
                //create user object to store all the details in the form must validate        
                    User usr= new User();
                    usr.setName(txt_usrname.getText());
                    usr.setNIC(txt_NIC.getText());
                    usr.setMobileNm(Integer.valueOf(txt_PhnNm.getText()));
                    usr.setDOB(thedate);
                    usr.setAdress(txtAr_Address.getText());
                    usr.setEmail(txt_Email.getText());
                    usr.setUserName(txt_UsrNm.getText());
                    
                    try {
                        usr.setPassword(pass.passwordEncord(Pass_pswrd.getText().toString().trim()));
                    } catch (NoSuchAlgorithmException ex) {
                            Logger.getLogger(user_reg.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                    
                    usr.setJobRole(combo_JRole.getSelectedItem().toString());

                //Establish connection to the firebase Database and give location to the saving node
                    FirebaseDatabase database = FirebaseDatabase.getInstance();
                    DatabaseReference myRef = database.getReference("Dentz/Users");
                //Upload and save and create selected data record in the database for mor details with completeion check
       
                myRef.push().setValue(usr, new DatabaseReference.CompletionListener() {
                    @Override
                    public void onComplete(DatabaseError de, DatabaseReference dr) {
                        if(de!=null){
                            JOptionPane.showMessageDialog(null, dr);
                        }else{
                            JOptionPane.showMessageDialog(null, "Data Saved Succesfully");
                            
                            //set Input field to null
                            txt_usrname.setText(null);
                            txt_NIC.setText(null);
                            Date_DOB.setDate(null);
                            txt_Email.setText(null);
                            txt_PhnNm.setText(null);
                            txtAr_Address.setText(null);
                            txt_UsrNm.setText(null);
                            Pass_pswrd.setText(null);
                        }
                            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }
                });
            }
        }
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseClicked

    }//GEN-LAST:event_btn_AddMouseClicked

    private void txt_UsrNmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsrNmKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsrNmKeyTyped

    private void txt_UsrNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsrNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsrNmActionPerformed

    private void txt_UsrNmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_UsrNmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsrNmMouseClicked

    private void txt_PhnNmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PhnNmKeyTyped
   //validate input length 
        if(txt_PhnNm.getText().length()>=10){
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter Valid Phone Number");
           txt_PhnNm.setText("");
            
       }
    }//GEN-LAST:event_txt_PhnNmKeyTyped

    private void txt_PhnNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PhnNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhnNmActionPerformed

    private void txt_PhnNmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PhnNmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PhnNmMouseClicked

    private void txt_EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailKeyTyped

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_EmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailMouseClicked

    private void txt_NICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NICKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NICKeyTyped

    private void txt_NICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NICActionPerformed

    private void txt_NICMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NICMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NICMouseClicked

    private void txt_usrnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usrnameKeyTyped

    }//GEN-LAST:event_txt_usrnameKeyTyped

    private void txt_usrnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usrnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usrnameActionPerformed

    private void txt_usrnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usrnameMouseClicked

    }//GEN-LAST:event_txt_usrnameMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        //login log = new login();
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked
 private static MessageDigest md;
    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        int result = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Cancel?",null,JOptionPane.YES_NO_OPTION);
        
        if(result == 0){
            this.dispose();
//            home hm = new home(log_name, user_role);
//            hm.setVisible(true);
        }else{
            System.out.println(result);
            
        }  
    }//GEN-LAST:event_btnCloseMouseClicked

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_reg().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_DOB;
    private javax.swing.JPasswordField Pass_pswrd;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMinimize;
    private keeptoo.KButton btn_Add;
    private keeptoo.KButton btn_update;
    private javax.swing.JComboBox<String> combo_JRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextArea txtAr_Address;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_NIC;
    private javax.swing.JTextField txt_PhnNm;
    private javax.swing.JTextField txt_UsrNm;
    private javax.swing.JTextField txt_usrname;
    // End of variables declaration//GEN-END:variables
}
